SET REDIST_NAME=vcredist_x86.exe
IF %PROCESSOR_ARCHITECTURE%==AMD64 SET REDIST_NAME=vcredist_x64.exe

PUSHD vcredist\vc2005
CALL %REDIST_NAME%
POPD

PUSHD vcredist\vc2008
CALL %REDIST_NAME%
POPD

pause
