// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#if !defined(AFX_STDAFX_H__70555192_9226_11D4_9230_00010270C860__INCLUDED_)

#include "WINSystemDefines.H"
#include "Rn_Defs.H"

#ifdef WIN32
#include <FL/gl.h>
#else
#include <GL/gl.h>
#endif


#endif // !defined(AFX_STDAFX_H__70555192_9226_11D4_9230_00010270C860__INCLUDED_)
