// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef UserInterface_h
#define UserInterface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "StdAfx.H"
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Adjuster.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include "JofGTIBar.H"

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *m_mainWindow;
  Fl_Slider *m_sldZoom;
private:
  inline void cb_m_sldZoom_i(Fl_Slider*, void*);
  static void cb_m_sldZoom(Fl_Slider*, void*);
public:
  Fl_Roller *m_rolRotAmt;
private:
  inline void cb_m_rolRotAmt_i(Fl_Roller*, void*);
  static void cb_m_rolRotAmt(Fl_Roller*, void*);
public:
  Fl_Dial *m_dialSpin;
private:
  inline void cb_m_dialSpin_i(Fl_Dial*, void*);
  static void cb_m_dialSpin(Fl_Dial*, void*);
public:
  Fl_Adjuster *m_adjXTrans;
private:
  inline void cb_m_adjXTrans_i(Fl_Adjuster*, void*);
  static void cb_m_adjXTrans(Fl_Adjuster*, void*);
public:
  Fl_Adjuster *m_adjYTrans;
private:
  inline void cb_m_adjYTrans_i(Fl_Adjuster*, void*);
  static void cb_m_adjYTrans(Fl_Adjuster*, void*);
public:
  Fl_Adjuster *m_adjInOut;
private:
  inline void cb_m_adjInOut_i(Fl_Adjuster*, void*);
  static void cb_m_adjInOut(Fl_Adjuster*, void*);
public:
  Fl_Roller *m_rolTransAmt;
private:
  inline void cb_m_rolTransAmt_i(Fl_Roller*, void*);
  static void cb_m_rolTransAmt(Fl_Roller*, void*);
  inline void cb_Reset_i(Fl_Button*, void*);
  static void cb_Reset(Fl_Button*, void*);
public:
  Fl_Roller *m_rolUpDown;
private:
  inline void cb_m_rolUpDown_i(Fl_Roller*, void*);
  static void cb_m_rolUpDown(Fl_Roller*, void*);
public:
  Fl_Roller *m_rolLeftRight;
private:
  inline void cb_m_rolLeftRight_i(Fl_Roller*, void*);
  static void cb_m_rolLeftRight(Fl_Roller*, void*);
  inline void cb_Zero_i(Fl_Button*, void*);
  static void cb_Zero(Fl_Button*, void*);
  inline void cb_IBar_i(Fl_Check_Button*, void*);
  static void cb_IBar(Fl_Check_Button*, void*);
  inline void cb_Center_i(Fl_Check_Button*, void*);
  static void cb_Center(Fl_Check_Button*, void*);
public:
  JofGTIBar *m_view;
  OGLObjsCamera & Camera();
  UserInterface();
};
#endif
