
.SUFFIXES: .cpp

WALK=/unc/walk
CFLAGS = 


#for sgi   -- comment out the lines below to use on HP
CC=CC -g0 -o32
ARCH=sgi_irix
CPPFLAGS=-I${WALK}/include -w 
GLLIBS=-L${WALK}/lib/${ARCH} -lglut -lGL -lGLU
LPATH=${GLUTPATH} 
INCS= 


#for hp   -- uncomment the lines below to use on HP
#CC=g++
#ARCH=hp700_hpux
#CPPFLAGS=-I${WALK}/include -w
#GLLIBS=-L/unc/walk/lib/hp700_hpux -lglut -L/unc/walk/lib/hp700_hpux/mesa -lGLU -lGL     
#LPATH= ${GLUTPATH} -L/usr/local/lib/X11
#INCS=-I/unc/walk/include/mesa -I/unc/walk/include -I. 



libs =     ${GLLIBS}  -lXmu -lXext -lX11 -lm -lmalloc 

LIBGLUI= -Llib -lglui

All: lib/libglui.a bin/example1 bin/example2 bin/example3 bin/example4

GLUI_OBJS = glui_add_controls.o glui.o glui_bitmap_img_data.o glui_bitmaps.o glui_button.o glui_edittext.o glui_checkbox.o glui_node.o glui_radio.o glui_statictext.o glui_panel.o glui_separator.o glui_spinner.o glui_control.o glui_column.o

example1: $(GLUI_OBJS) example1.o
	@echo "Linking example1"
	$(CC)  $(CFLAG) $(CPPFLAGS) $(LPATH) example1.o $(LIBGLUI) $(libs) -o bin/example1

example2: $(GLUI_OBJS) example2.o
	@echo "Linking example2"
	$(CC)  $(CFLAG) $(CPPFLAGS) $(LPATH) example2.o $(LIBGLUI) $(libs) -o bin/example2

example3: $(GLUI_OBJS) example3.o
	@echo "Linking example3"
	$(CC)  $(CFLAG) $(CPPFLAGS) $(LPATH) example3.o $(LIBGLUI) $(libs) -o bin/example3

example4: $(GLUI_OBJS) example4.o
	@echo "Linking example4"
	$(CC)  $(CFLAG) $(CPPFLAGS) $(LPATH) example4.o $(LIBGLUI) $(libs) -o bin/example4

lib/libglui.a: $(GLUI_OBJS)
	@echo "Creating library"
	ar -r lib/libglui.a $(GLUI_OBJS)

.cpp.o:
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(INCS) $*.cpp

.c.o:
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(INCS) $*.c
clean:
	/bin/rm *.o


# DO NOT DELETE THIS LINE -- make depend depends on it.

algebra3.o: /usr/include/math.h /usr/include/sgidefs.h
algebra3.o: /usr/include/standards.h algebra3.h /usr/include/stdio.h
algebra3.o: /usr/include/stdlib.h /usr/include/ctype.h
arcball.o: arcball.h algebra3.h /usr/include/math.h /usr/include/sgidefs.h
arcball.o: /usr/include/standards.h /usr/include/stdio.h
arcball.o: /usr/include/stdlib.h quaternion.h stdinc.h
example1.o: /usr/include/string.h /usr/include/standards.h glui.h
example1.o: /usr/include/stdlib.h /usr/include/sgidefs.h /usr/include/stdio.h
example2.o: /usr/include/string.h /usr/include/standards.h glui.h
example2.o: /usr/include/stdlib.h /usr/include/sgidefs.h /usr/include/stdio.h
example3.o: /usr/include/string.h /usr/include/standards.h glui.h
example3.o: /usr/include/stdlib.h /usr/include/sgidefs.h /usr/include/stdio.h
example4.o: /usr/include/string.h /usr/include/standards.h glui.h
example4.o: /usr/include/stdlib.h /usr/include/sgidefs.h /usr/include/stdio.h
glui.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui.o: /usr/include/sgidefs.h /usr/include/stdio.h /usr/include/string.h
glui.o: stdinc.h /usr/include/math.h
glui_add_controls.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_add_controls.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_add_controls.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_bitmap_img_data.o: glui_img_checkbox_0.c glui_img_checkbox_1.c
glui_bitmap_img_data.o: glui_img_radiobutton_0.c glui_img_radiobutton_1.c
glui_bitmap_img_data.o: glui_img_uparrow.c glui_img_downarrow.c
glui_bitmap_img_data.o: glui_img_leftarrow.c glui_img_rightarrow.c
glui_bitmap_img_data.o: glui_img_spinup_1.c glui_img_spinup_0.c
glui_bitmap_img_data.o: glui_img_spindown_1.c glui_img_spindown_0.c
glui_bitmap_img_data.o: glui_img_checkbox_0_dis.c glui_img_checkbox_1_dis.c
glui_bitmap_img_data.o: glui_img_radiobutton_0_dis.c
glui_bitmap_img_data.o: glui_img_radiobutton_1_dis.c glui_img_spinup_dis.c
glui_bitmap_img_data.o: glui_img_spindown_dis.c
glui_bitmaps.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_bitmaps.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_bitmaps.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_button.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_button.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_button.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_checkbox.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_checkbox.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_checkbox.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_column.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_column.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_column.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_control.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_control.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_control.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_edittext.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_edittext.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_edittext.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_node.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_node.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_node.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_panel.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_panel.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_panel.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_radio.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_radio.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_radio.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_separator.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_separator.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_separator.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_spinner.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_spinner.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_spinner.o: /usr/include/string.h stdinc.h /usr/include/math.h
glui_statictext.o: glui.h /usr/include/stdlib.h /usr/include/standards.h
glui_statictext.o: /usr/include/sgidefs.h /usr/include/stdio.h
glui_statictext.o: /usr/include/string.h stdinc.h /usr/include/math.h
ppm2array.o: /usr/include/stdio.h /usr/include/standards.h
ppm2array.o: /usr/include/sgidefs.h
quaternion.o: quaternion.h algebra3.h /usr/include/math.h
quaternion.o: /usr/include/sgidefs.h /usr/include/standards.h
quaternion.o: /usr/include/stdio.h /usr/include/stdlib.h stdinc.h
