override SOURCEROOT	= ../..
CXXFLAGS += -DGLEW_STATIC
PROGRAMS 		= pointviewer pointgen
OWN_LIBS 		= LDI Graphics Components CGLA GLUI 
LIBS				= ${GLUTLIBS} ${GLLIBS}
include ${SOURCEROOT}/makefiles/application.mk
