DEBIAN_VERSION = ${shell head -1 debian/changelog 2>/dev/null | sed -e '1s,.*(\([^)]*\)).*,\1,'}
DEBIAN_ARCH = $(shell test -x `which dpkg-architecture 2>/dev/null` && dpkg-architecture -qDEB_BUILD_ARCH 2>/dev/null || echo i386)

TARBALL = $(distdir).tar.gz
DEBDIR = .debian
STAMP = $(DEBDIR)/stamp
DISTDIR = $(DEBDIR)/$(distdir)
CHANGES = $(DEBDIR)/@PACKAGE@_$(DEBIAN_VERSION)_$(DEBIAN_ARCH).changes
UPLOAD = $(DEBDIR)/@PACKAGE@_$(DEBIAN_VERSION)_$(DEBIAN_ARCH).upload

$(TARBALL):
	$(error run 'make dist' to create the tarball)

$(STAMP): $(TARBALL)
	mkdir -p $(DEBDIR)
	tar xfz $(TARBALL) -C $(DEBDIR)
	cp -r $(DISTDIR) $(DISTDIR).orig
	rm -rf $(DISTDIR).orig/debian
	touch $@

$(CHANGES): $(STAMP)
	cd $(DISTDIR) && debuild -uc -us
	dpkg-sig --cache-passphrase --sign-changes full --sign builder $@

$(DEBDIR)/dupload.conf: dupload.conf
	ln -f $< $@

$(UPLOAD): $(CHANGES) $(DEBDIR)/dupload.conf
	cd $(DEBDIR) && dupload -c --to pdo

.PHONY: debian
debian: $(CHANGES)
	@echo "Debian packages for version $(DEBIAN_VERSION) built in .debian subdirectory"

.PHONY: dupload
dupload: $(UPLOAD)
	@echo "Debian packages uploaded."

.PHONY: debclean
debclean:
	rm -rf $(DEBDIR)

# COPYRIGHT --
#
# This file is part of libkdtree++, a C++ template KD-Tree sorting container.
# libkdtree++ is (c) 2004 Martin F. Krafft <krafft@ailab.ch>
# and distributed under the terms of the Artistic Licence.
# See the ./COPYING file in the source tree root for more information.
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES
# OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
