INCLUDE =
CCFLAGS = -g $(INCLUDE)

LIBDIR = -L/home/adrian/lib/i386-elf

CXX = g++ $(CCFLAGS)
CCC = $(CXX)

LIBOBJS = tessellate.o

TESSOBJS = trytess.o $(LIBOBJS)



trytess: $(TESSOBJS)
	g++ $(LIBDIR) -o $@ $(TESSOBJS)


clean:
	rm *.o core trytess

depend:
	makedepend $(INCLUDE) *.cc *.h

# DO NOT DELETE THIS LINE -- make depend depends on it.

tessellate.o: tessellate.h
trytess.o: /home/adrian/c++include/my_io.h /usr/include/strings.h
trytess.o: /usr/include/features.h /usr/include/sys/cdefs.h
trytess.o: /usr/include/gnu/stubs.h /usr/include/string.h
trytess.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/bytesex.h
trytess.o: tessellate.h tessellate.cc /usr/include/stdlib.h
trytess.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess.o: /usr/include/time.h /usr/include/sys/select.h
trytess.o: /usr/include/selectbits.h /usr/include/alloca.h
trytess1.o: tessellate.h /usr/include/stdlib.h /usr/include/features.h
trytess1.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
trytess1.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess1.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess1.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
trytess1.o: /usr/include/sys/select.h /usr/include/selectbits.h
trytess1.o: /usr/include/alloca.h
trytess2.o: tessellate.h /usr/include/stdlib.h /usr/include/features.h
trytess2.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
trytess2.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess2.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess2.o: /usr/include/time.h /usr/include/endian.h /usr/include/bytesex.h
trytess2.o: /usr/include/sys/select.h /usr/include/selectbits.h
trytess2.o: /usr/include/alloca.h
trytess3.o: /home/adrian/c++include/my_io.h /usr/include/strings.h
trytess3.o: /usr/include/features.h /usr/include/sys/cdefs.h
trytess3.o: /usr/include/gnu/stubs.h /usr/include/string.h
trytess3.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess3.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/bytesex.h
trytess3.o: tessellate.h tessellate.cc /usr/include/stdlib.h
trytess3.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess3.o: /usr/include/time.h /usr/include/sys/select.h
trytess3.o: /usr/include/selectbits.h /usr/include/alloca.h
trytess4.o: /home/adrian/c++include/my_io.h /usr/include/strings.h
trytess4.o: /usr/include/features.h /usr/include/sys/cdefs.h
trytess4.o: /usr/include/gnu/stubs.h /usr/include/string.h
trytess4.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess4.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/bytesex.h
trytess4.o: tessellate.h tessellate.cc /usr/include/stdlib.h
trytess4.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess4.o: /usr/include/time.h /usr/include/sys/select.h
trytess4.o: /usr/include/selectbits.h /usr/include/alloca.h
trytess5.o: /home/adrian/c++include/my_io.h /usr/include/strings.h
trytess5.o: /usr/include/features.h /usr/include/sys/cdefs.h
trytess5.o: /usr/include/gnu/stubs.h /usr/include/string.h
trytess5.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
trytess5.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/bytesex.h
trytess5.o: tessellate.h tessellate.cc /usr/include/stdlib.h
trytess5.o: /usr/include/sys/types.h /usr/include/gnu/types.h
trytess5.o: /usr/include/time.h /usr/include/sys/select.h
trytess5.o: /usr/include/selectbits.h /usr/include/alloca.h
